use ChessLive;

create table PLAYER(
    ID varchar(128) PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(50) unique NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    JOIN_DATE DATETIME
);

CREATE TABLE GAME (
    ID varchar(128) PRIMARY KEY NOT NUll,
    WHITE varchar(128),
    BLACK varchar(128),
    `DATE` DATETIME not null,
    TIME_CONTROL VARCHAR(50) not null,
    PGN VARCHAR(200),
    RESULT VARCHAR(20),
    FOREIGN KEY(WHITE) REFERENCES PLAYER(ID),
    FOREIGN KEY(BLACK) REFERENCES PLAYER(ID)
);

CREATE TABLE STATISTICS(
	ID varchar(128) primary KEY NOT NULL,
    USERNAME varchar(50),
    TWO_PLUS_1_WINS int DEFAULT 0,
    TWO_PLUS_1_LOSSES int DEFAULT 0,
    TWO_PLUS_1_DRAWS int DEFAULT 0,
    
    FIVE_PLUS_0_WINS int DEFAULT 0,
    FIVE_PLUS_0_LOSSES int DEFAULT 0,
    FIVE_PLUS_0_DRAWS int DEFAULT 0,
    
    FIVE_PLUS_5_WINS int DEFAULT 0,
    FIVE_PLUS_5_LOSSES int DEFAULT 0,
    FIVE_PLUS_5_DRAWS int DEFAULT 0,
    
    TEN_PLUS_10_WINS int DEFAULT 0,
    TEN_PLUS_10_LOSSES int DEFAULT 0,
    TEN_PLUS_10_DRAWS int DEFAULT 0
);